FROM golang:1.26-bookworm

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        bpftrace \
        clang \
        llvm \
        build-essential \
        pkg-config \
        ca-certificates \
        curl \
        jq \
        sqlite3 \
        iproute2 \
        procps && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /workspace
