// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package db

import (
	"context"
	"database/sql"
)

const addBridgedAccount = `-- name: AddBridgedAccount :exec
INSERT INTO bridged_accounts (at_did, ssb_feed_id, active)
VALUES (?1, ?2, ?3)
ON CONFLICT(at_did) DO UPDATE SET
    ssb_feed_id = excluded.ssb_feed_id,
    active = excluded.active
`

type AddBridgedAccountParams struct {
	AtDid     string
	SsbFeedID string
	Active    sql.NullBool
}

func (q *Queries) AddBridgedAccount(ctx context.Context, arg AddBridgedAccountParams) error {
	_, err := q.db.ExecContext(ctx, addBridgedAccount, arg.AtDid, arg.SsbFeedID, arg.Active)
	return err
}

const countActiveBridgedAccounts = `-- name: CountActiveBridgedAccounts :one
SELECT COUNT(*) FROM bridged_accounts WHERE active = 1
`

func (q *Queries) CountActiveBridgedAccounts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveBridgedAccounts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBridgedAccounts = `-- name: CountBridgedAccounts :one
SELECT COUNT(*) FROM bridged_accounts
`

func (q *Queries) CountBridgedAccounts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBridgedAccounts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getActiveBridgedAccountWithStats = `-- name: GetActiveBridgedAccountWithStats :one
SELECT
  ba.at_did,
  ba.ssb_feed_id,
  ba.created_at,
  ba.active,
  COALESCE(s.total_messages, 0) as total_messages,
  COALESCE(s.published_messages, 0) as published_messages,
  COALESCE(s.failed_messages, 0) as failed_messages,
  COALESCE(s.deferred_messages, 0) as deferred_messages,
  s.last_published_at
FROM bridged_accounts ba
LEFT JOIN (
  SELECT
    at_did,
    COUNT(*)                                                       AS total_messages,
    SUM(CASE WHEN message_state = 'published' THEN 1 ELSE 0 END)  AS published_messages,
    SUM(CASE WHEN message_state = 'failed' THEN 1 ELSE 0 END)     AS failed_messages,
    SUM(CASE WHEN message_state = 'deferred' THEN 1 ELSE 0 END)   AS deferred_messages,
    MAX(published_at)                                              AS last_published_at
  FROM messages
  GROUP BY at_did
) s ON s.at_did = ba.at_did
WHERE ba.active = 1 AND ba.at_did = ?1
`

type GetActiveBridgedAccountWithStatsRow struct {
	AtDid             string
	SsbFeedID         string
	CreatedAt         sql.NullTime
	Active            sql.NullBool
	TotalMessages     int64
	PublishedMessages float64
	FailedMessages    float64
	DeferredMessages  float64
	LastPublishedAt   interface{}
}

func (q *Queries) GetActiveBridgedAccountWithStats(ctx context.Context, atDid string) (GetActiveBridgedAccountWithStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getActiveBridgedAccountWithStats, atDid)
	var i GetActiveBridgedAccountWithStatsRow
	err := row.Scan(
		&i.AtDid,
		&i.SsbFeedID,
		&i.CreatedAt,
		&i.Active,
		&i.TotalMessages,
		&i.PublishedMessages,
		&i.FailedMessages,
		&i.DeferredMessages,
		&i.LastPublishedAt,
	)
	return i, err
}

const getAllBridgedAccounts = `-- name: GetAllBridgedAccounts :many
SELECT at_did, ssb_feed_id, created_at, active FROM bridged_accounts ORDER BY created_at DESC
`

func (q *Queries) GetAllBridgedAccounts(ctx context.Context) ([]BridgedAccount, error) {
	rows, err := q.db.QueryContext(ctx, getAllBridgedAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BridgedAccount
	for rows.Next() {
		var i BridgedAccount
		if err := rows.Scan(
			&i.AtDid,
			&i.SsbFeedID,
			&i.CreatedAt,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBridgedAccount = `-- name: GetBridgedAccount :one
SELECT at_did, ssb_feed_id, created_at, active FROM bridged_accounts WHERE at_did = ?1
`

func (q *Queries) GetBridgedAccount(ctx context.Context, atDid string) (BridgedAccount, error) {
	row := q.db.QueryRowContext(ctx, getBridgedAccount, atDid)
	var i BridgedAccount
	err := row.Scan(
		&i.AtDid,
		&i.SsbFeedID,
		&i.CreatedAt,
		&i.Active,
	)
	return i, err
}

const listActiveBridgedAccounts = `-- name: ListActiveBridgedAccounts :many
SELECT at_did, ssb_feed_id, created_at, active FROM bridged_accounts WHERE active = 1 ORDER BY created_at DESC
`

func (q *Queries) ListActiveBridgedAccounts(ctx context.Context) ([]BridgedAccount, error) {
	rows, err := q.db.QueryContext(ctx, listActiveBridgedAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BridgedAccount
	for rows.Next() {
		var i BridgedAccount
		if err := rows.Scan(
			&i.AtDid,
			&i.SsbFeedID,
			&i.CreatedAt,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveBridgedAccountsWithStats = `-- name: ListActiveBridgedAccountsWithStats :many
SELECT
  ba.at_did,
  ba.ssb_feed_id,
  ba.created_at,
  ba.active,
  COALESCE(s.total_messages, 0) as total_messages,
  COALESCE(s.published_messages, 0) as published_messages,
  COALESCE(s.failed_messages, 0) as failed_messages,
  COALESCE(s.deferred_messages, 0) as deferred_messages,
  s.last_published_at
FROM bridged_accounts ba
LEFT JOIN (
  SELECT
    at_did,
    COUNT(*)                                                       AS total_messages,
    SUM(CASE WHEN message_state = 'published' THEN 1 ELSE 0 END)  AS published_messages,
    SUM(CASE WHEN message_state = 'failed' THEN 1 ELSE 0 END)     AS failed_messages,
    SUM(CASE WHEN message_state = 'deferred' THEN 1 ELSE 0 END)   AS deferred_messages,
    MAX(published_at)                                              AS last_published_at
  FROM messages
  GROUP BY at_did
) s ON s.at_did = ba.at_did
WHERE ba.active = 1
ORDER BY ba.created_at DESC
`

type ListActiveBridgedAccountsWithStatsRow struct {
	AtDid             string
	SsbFeedID         string
	CreatedAt         sql.NullTime
	Active            sql.NullBool
	TotalMessages     int64
	PublishedMessages float64
	FailedMessages    float64
	DeferredMessages  float64
	LastPublishedAt   interface{}
}

func (q *Queries) ListActiveBridgedAccountsWithStats(ctx context.Context) ([]ListActiveBridgedAccountsWithStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveBridgedAccountsWithStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveBridgedAccountsWithStatsRow
	for rows.Next() {
		var i ListActiveBridgedAccountsWithStatsRow
		if err := rows.Scan(
			&i.AtDid,
			&i.SsbFeedID,
			&i.CreatedAt,
			&i.Active,
			&i.TotalMessages,
			&i.PublishedMessages,
			&i.FailedMessages,
			&i.DeferredMessages,
			&i.LastPublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveBridgedAccountsWithStatsSorted = `-- name: ListActiveBridgedAccountsWithStatsSorted :many
SELECT
  ba.at_did,
  ba.ssb_feed_id,
  ba.created_at,
  ba.active,
  COALESCE(s.total_messages, 0) as total_messages,
  COALESCE(s.published_messages, 0) as published_messages,
  COALESCE(s.failed_messages, 0) as failed_messages,
  COALESCE(s.deferred_messages, 0) as deferred_messages,
  s.last_published_at
FROM bridged_accounts ba
LEFT JOIN (
  SELECT
    at_did,
    COUNT(*)                                                       AS total_messages,
    SUM(CASE WHEN message_state = 'published' THEN 1 ELSE 0 END)  AS published_messages,
    SUM(CASE WHEN message_state = 'failed' THEN 1 ELSE 0 END)     AS failed_messages,
    SUM(CASE WHEN message_state = 'deferred' THEN 1 ELSE 0 END)   AS deferred_messages,
    MAX(published_at)                                              AS last_published_at
  FROM messages
  GROUP BY at_did
) s ON s.at_did = ba.at_did
WHERE ba.active = 1
ORDER BY ba.created_at DESC
`

type ListActiveBridgedAccountsWithStatsSortedRow struct {
	AtDid             string
	SsbFeedID         string
	CreatedAt         sql.NullTime
	Active            sql.NullBool
	TotalMessages     int64
	PublishedMessages float64
	FailedMessages    float64
	DeferredMessages  float64
	LastPublishedAt   interface{}
}

func (q *Queries) ListActiveBridgedAccountsWithStatsSorted(ctx context.Context) ([]ListActiveBridgedAccountsWithStatsSortedRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveBridgedAccountsWithStatsSorted)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveBridgedAccountsWithStatsSortedRow
	for rows.Next() {
		var i ListActiveBridgedAccountsWithStatsSortedRow
		if err := rows.Scan(
			&i.AtDid,
			&i.SsbFeedID,
			&i.CreatedAt,
			&i.Active,
			&i.TotalMessages,
			&i.PublishedMessages,
			&i.FailedMessages,
			&i.DeferredMessages,
			&i.LastPublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBridgedAccountsWithStats = `-- name: ListBridgedAccountsWithStats :many
SELECT
  ba.at_did,
  ba.ssb_feed_id,
  ba.created_at,
  ba.active,
  COALESCE(s.total_messages, 0) as total_messages,
  COALESCE(s.published_messages, 0) as published_messages,
  COALESCE(s.failed_messages, 0) as failed_messages,
  COALESCE(s.deferred_messages, 0) as deferred_messages,
  s.last_published_at
FROM bridged_accounts ba
LEFT JOIN (
  SELECT
    at_did,
    COUNT(*)                                                       AS total_messages,
    SUM(CASE WHEN message_state = 'published' THEN 1 ELSE 0 END)  AS published_messages,
    SUM(CASE WHEN message_state = 'failed' THEN 1 ELSE 0 END)     AS failed_messages,
    SUM(CASE WHEN message_state = 'deferred' THEN 1 ELSE 0 END)   AS deferred_messages,
    MAX(published_at)                                              AS last_published_at
  FROM messages
  GROUP BY at_did
) s ON s.at_did = ba.at_did
ORDER BY ba.created_at DESC
`

type ListBridgedAccountsWithStatsRow struct {
	AtDid             string
	SsbFeedID         string
	CreatedAt         sql.NullTime
	Active            sql.NullBool
	TotalMessages     int64
	PublishedMessages float64
	FailedMessages    float64
	DeferredMessages  float64
	LastPublishedAt   interface{}
}

func (q *Queries) ListBridgedAccountsWithStats(ctx context.Context) ([]ListBridgedAccountsWithStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, listBridgedAccountsWithStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBridgedAccountsWithStatsRow
	for rows.Next() {
		var i ListBridgedAccountsWithStatsRow
		if err := rows.Scan(
			&i.AtDid,
			&i.SsbFeedID,
			&i.CreatedAt,
			&i.Active,
			&i.TotalMessages,
			&i.PublishedMessages,
			&i.FailedMessages,
			&i.DeferredMessages,
			&i.LastPublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeBridgedAccount = `-- name: RemoveBridgedAccount :exec
DELETE FROM bridged_accounts WHERE at_did = ?1
`

func (q *Queries) RemoveBridgedAccount(ctx context.Context, atDid string) error {
	_, err := q.db.ExecContext(ctx, removeBridgedAccount, atDid)
	return err
}
