// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: atproto.sql

package db

import (
	"context"
	"database/sql"
)

const addATProtoCommitBufferItem = `-- name: AddATProtoCommitBufferItem :exec
INSERT INTO atproto_commit_buffer (did, generation, rev, seq, raw_event_json)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(did, generation, rev) DO UPDATE SET
	seq=excluded.seq,
	raw_event_json=excluded.raw_event_json
`

type AddATProtoCommitBufferItemParams struct {
	Did          string
	Generation   int64
	Rev          string
	Seq          int64
	RawEventJson string
}

func (q *Queries) AddATProtoCommitBufferItem(ctx context.Context, arg AddATProtoCommitBufferItemParams) error {
	_, err := q.db.ExecContext(ctx, addATProtoCommitBufferItem,
		arg.Did,
		arg.Generation,
		arg.Rev,
		arg.Seq,
		arg.RawEventJson,
	)
	return err
}

const appendATProtoEvent = `-- name: AppendATProtoEvent :exec
INSERT INTO atproto_event_log (did, collection, rkey, at_uri, at_cid, action, live, rev, seq, record_json)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type AppendATProtoEventParams struct {
	Did        string
	Collection string
	Rkey       string
	AtUri      string
	AtCid      sql.NullString
	Action     string
	Live       bool
	Rev        sql.NullString
	Seq        sql.NullInt64
	RecordJson sql.NullString
}

func (q *Queries) AppendATProtoEvent(ctx context.Context, arg AppendATProtoEventParams) error {
	_, err := q.db.ExecContext(ctx, appendATProtoEvent,
		arg.Did,
		arg.Collection,
		arg.Rkey,
		arg.AtUri,
		arg.AtCid,
		arg.Action,
		arg.Live,
		arg.Rev,
		arg.Seq,
		arg.RecordJson,
	)
	return err
}

const deleteATProtoCommitBufferItems = `-- name: DeleteATProtoCommitBufferItems :exec
DELETE FROM atproto_commit_buffer WHERE did = ? AND generation = ?
`

type DeleteATProtoCommitBufferItemsParams struct {
	Did        string
	Generation int64
}

func (q *Queries) DeleteATProtoCommitBufferItems(ctx context.Context, arg DeleteATProtoCommitBufferItemsParams) error {
	_, err := q.db.ExecContext(ctx, deleteATProtoCommitBufferItems, arg.Did, arg.Generation)
	return err
}

const getATProtoRecord = `-- name: GetATProtoRecord :one
SELECT did, collection, rkey, at_uri, at_cid, record_json, last_rev, last_seq, deleted, deleted_at, created_at, updated_at
FROM atproto_records
WHERE at_uri = ?
`

func (q *Queries) GetATProtoRecord(ctx context.Context, atUri string) (AtprotoRecord, error) {
	row := q.db.QueryRowContext(ctx, getATProtoRecord, atUri)
	var i AtprotoRecord
	err := row.Scan(
		&i.Did,
		&i.Collection,
		&i.Rkey,
		&i.AtUri,
		&i.AtCid,
		&i.RecordJson,
		&i.LastRev,
		&i.LastSeq,
		&i.Deleted,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getATProtoRepo = `-- name: GetATProtoRepo :one
SELECT did, tracking, reason, sync_state, generation, current_rev, current_commit_cid, current_data_cid,
	   last_firehose_seq, last_backfill_at, last_event_cursor, handle, pds_url, account_active,
	   account_status, last_identity_at, last_account_at, last_error, created_at, updated_at
FROM atproto_repos
WHERE did = ?
`

func (q *Queries) GetATProtoRepo(ctx context.Context, did string) (AtprotoRepo, error) {
	row := q.db.QueryRowContext(ctx, getATProtoRepo, did)
	var i AtprotoRepo
	err := row.Scan(
		&i.Did,
		&i.Tracking,
		&i.Reason,
		&i.SyncState,
		&i.Generation,
		&i.CurrentRev,
		&i.CurrentCommitCid,
		&i.CurrentDataCid,
		&i.LastFirehoseSeq,
		&i.LastBackfillAt,
		&i.LastEventCursor,
		&i.Handle,
		&i.PdsUrl,
		&i.AccountActive,
		&i.AccountStatus,
		&i.LastIdentityAt,
		&i.LastAccountAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getATProtoSource = `-- name: GetATProtoSource :one
SELECT source_key, relay_url, last_seq, connected_at, updated_at
FROM atproto_sources
WHERE source_key = ?
`

func (q *Queries) GetATProtoSource(ctx context.Context, sourceKey string) (AtprotoSource, error) {
	row := q.db.QueryRowContext(ctx, getATProtoSource, sourceKey)
	var i AtprotoSource
	err := row.Scan(
		&i.SourceKey,
		&i.RelayUrl,
		&i.LastSeq,
		&i.ConnectedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestATProtoEventCursor = `-- name: GetLatestATProtoEventCursor :one
SELECT cursor
FROM atproto_event_log
ORDER BY cursor DESC
LIMIT 1
`

func (q *Queries) GetLatestATProtoEventCursor(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getLatestATProtoEventCursor)
	var cursor int64
	err := row.Scan(&cursor)
	return cursor, err
}

const listATProtoCommitBufferItems = `-- name: ListATProtoCommitBufferItems :many
SELECT id, did, generation, rev, seq, raw_event_json, created_at
FROM atproto_commit_buffer
WHERE did = ? AND generation = ?
ORDER BY seq, rev
`

type ListATProtoCommitBufferItemsParams struct {
	Did        string
	Generation int64
}

func (q *Queries) ListATProtoCommitBufferItems(ctx context.Context, arg ListATProtoCommitBufferItemsParams) ([]AtprotoCommitBuffer, error) {
	rows, err := q.db.QueryContext(ctx, listATProtoCommitBufferItems, arg.Did, arg.Generation)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AtprotoCommitBuffer
	for rows.Next() {
		var i AtprotoCommitBuffer
		if err := rows.Scan(
			&i.ID,
			&i.Did,
			&i.Generation,
			&i.Rev,
			&i.Seq,
			&i.RawEventJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listATProtoEventsAfter = `-- name: ListATProtoEventsAfter :many
SELECT cursor, did, collection, rkey, at_uri, at_cid, action, live, rev, seq, record_json, created_at
FROM atproto_event_log
WHERE cursor > ?
ORDER BY cursor
LIMIT ?
`

type ListATProtoEventsAfterParams struct {
	Cursor int64
	Limit  int64
}

func (q *Queries) ListATProtoEventsAfter(ctx context.Context, arg ListATProtoEventsAfterParams) ([]AtprotoEventLog, error) {
	rows, err := q.db.QueryContext(ctx, listATProtoEventsAfter, arg.Cursor, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AtprotoEventLog
	for rows.Next() {
		var i AtprotoEventLog
		if err := rows.Scan(
			&i.Cursor,
			&i.Did,
			&i.Collection,
			&i.Rkey,
			&i.AtUri,
			&i.AtCid,
			&i.Action,
			&i.Live,
			&i.Rev,
			&i.Seq,
			&i.RecordJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listATProtoRecords = `-- name: ListATProtoRecords :many
SELECT did, collection, rkey, at_uri, at_cid, record_json, last_rev, last_seq, deleted, deleted_at, created_at, updated_at
FROM atproto_records
WHERE did = ? AND collection = ?
ORDER BY at_uri
LIMIT ?
`

type ListATProtoRecordsParams struct {
	Did        string
	Collection string
	Limit      int64
}

func (q *Queries) ListATProtoRecords(ctx context.Context, arg ListATProtoRecordsParams) ([]AtprotoRecord, error) {
	rows, err := q.db.QueryContext(ctx, listATProtoRecords, arg.Did, arg.Collection, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AtprotoRecord
	for rows.Next() {
		var i AtprotoRecord
		if err := rows.Scan(
			&i.Did,
			&i.Collection,
			&i.Rkey,
			&i.AtUri,
			&i.AtCid,
			&i.RecordJson,
			&i.LastRev,
			&i.LastSeq,
			&i.Deleted,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrackedATProtoRepos = `-- name: ListTrackedATProtoRepos :many
SELECT did, tracking, reason, sync_state, generation, current_rev, current_commit_cid, current_data_cid,
	   last_firehose_seq, last_backfill_at, last_event_cursor, handle, pds_url, account_active,
	   account_status, last_identity_at, last_account_at, last_error, created_at, updated_at
FROM atproto_repos
WHERE tracking = 1
ORDER BY did
`

func (q *Queries) ListTrackedATProtoRepos(ctx context.Context) ([]AtprotoRepo, error) {
	rows, err := q.db.QueryContext(ctx, listTrackedATProtoRepos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AtprotoRepo
	for rows.Next() {
		var i AtprotoRepo
		if err := rows.Scan(
			&i.Did,
			&i.Tracking,
			&i.Reason,
			&i.SyncState,
			&i.Generation,
			&i.CurrentRev,
			&i.CurrentCommitCid,
			&i.CurrentDataCid,
			&i.LastFirehoseSeq,
			&i.LastBackfillAt,
			&i.LastEventCursor,
			&i.Handle,
			&i.PdsUrl,
			&i.AccountActive,
			&i.AccountStatus,
			&i.LastIdentityAt,
			&i.LastAccountAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertATProtoRecord = `-- name: UpsertATProtoRecord :exec
INSERT INTO atproto_records (did, collection, rkey, at_uri, at_cid, record_json, last_rev, last_seq, deleted, deleted_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(did, collection, rkey) DO UPDATE SET
	at_uri=excluded.at_uri,
	at_cid=excluded.at_cid,
	record_json=excluded.record_json,
	last_rev=excluded.last_rev,
	last_seq=excluded.last_seq,
	deleted=excluded.deleted,
	deleted_at=excluded.deleted_at,
	updated_at=CURRENT_TIMESTAMP
`

type UpsertATProtoRecordParams struct {
	Did        string
	Collection string
	Rkey       string
	AtUri      string
	AtCid      string
	RecordJson string
	LastRev    sql.NullString
	LastSeq    sql.NullInt64
	Deleted    bool
	DeletedAt  sql.NullTime
}

func (q *Queries) UpsertATProtoRecord(ctx context.Context, arg UpsertATProtoRecordParams) error {
	_, err := q.db.ExecContext(ctx, upsertATProtoRecord,
		arg.Did,
		arg.Collection,
		arg.Rkey,
		arg.AtUri,
		arg.AtCid,
		arg.RecordJson,
		arg.LastRev,
		arg.LastSeq,
		arg.Deleted,
		arg.DeletedAt,
	)
	return err
}

const upsertATProtoRepo = `-- name: UpsertATProtoRepo :exec
INSERT INTO atproto_repos (
	did, tracking, reason, sync_state, generation, current_rev, current_commit_cid, current_data_cid,
	last_firehose_seq, last_backfill_at, last_event_cursor, handle, pds_url, account_active,
	account_status, last_identity_at, last_account_at, last_error, updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(did) DO UPDATE SET
	tracking=excluded.tracking,
	reason=excluded.reason,
	sync_state=excluded.sync_state,
	generation=excluded.generation,
	current_rev=excluded.current_rev,
	current_commit_cid=excluded.current_commit_cid,
	current_data_cid=excluded.current_data_cid,
	last_firehose_seq=excluded.last_firehose_seq,
	last_backfill_at=excluded.last_backfill_at,
	last_event_cursor=excluded.last_event_cursor,
	handle=excluded.handle,
	pds_url=excluded.pds_url,
	account_active=excluded.account_active,
	account_status=excluded.account_status,
	last_identity_at=excluded.last_identity_at,
	last_account_at=excluded.last_account_at,
	last_error=excluded.last_error,
	updated_at=CURRENT_TIMESTAMP
`

type UpsertATProtoRepoParams struct {
	Did              string
	Tracking         bool
	Reason           sql.NullString
	SyncState        string
	Generation       int64
	CurrentRev       sql.NullString
	CurrentCommitCid sql.NullString
	CurrentDataCid   sql.NullString
	LastFirehoseSeq  sql.NullInt64
	LastBackfillAt   sql.NullTime
	LastEventCursor  sql.NullInt64
	Handle           sql.NullString
	PdsUrl           sql.NullString
	AccountActive    sql.NullBool
	AccountStatus    sql.NullString
	LastIdentityAt   sql.NullTime
	LastAccountAt    sql.NullTime
	LastError        sql.NullString
}

func (q *Queries) UpsertATProtoRepo(ctx context.Context, arg UpsertATProtoRepoParams) error {
	_, err := q.db.ExecContext(ctx, upsertATProtoRepo,
		arg.Did,
		arg.Tracking,
		arg.Reason,
		arg.SyncState,
		arg.Generation,
		arg.CurrentRev,
		arg.CurrentCommitCid,
		arg.CurrentDataCid,
		arg.LastFirehoseSeq,
		arg.LastBackfillAt,
		arg.LastEventCursor,
		arg.Handle,
		arg.PdsUrl,
		arg.AccountActive,
		arg.AccountStatus,
		arg.LastIdentityAt,
		arg.LastAccountAt,
		arg.LastError,
	)
	return err
}

const upsertATProtoSource = `-- name: UpsertATProtoSource :exec
INSERT INTO atproto_sources (source_key, relay_url, last_seq, connected_at, updated_at)
VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(source_key) DO UPDATE SET
	relay_url=excluded.relay_url,
	last_seq=excluded.last_seq,
	connected_at=excluded.connected_at,
	updated_at=CURRENT_TIMESTAMP
`

type UpsertATProtoSourceParams struct {
	SourceKey   string
	RelayUrl    string
	LastSeq     int64
	ConnectedAt sql.NullTime
}

func (q *Queries) UpsertATProtoSource(ctx context.Context, arg UpsertATProtoSourceParams) error {
	_, err := q.db.ExecContext(ctx, upsertATProtoSource,
		arg.SourceKey,
		arg.RelayUrl,
		arg.LastSeq,
		arg.ConnectedAt,
	)
	return err
}
