// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: blobs.sql

package db

import (
	"context"
	"database/sql"
)

const addBlob = `-- name: AddBlob :exec
INSERT INTO blobs (at_cid, ssb_blob_ref, size, mime_type)
VALUES (?1, ?2, ?3, ?4)
ON CONFLICT(at_cid) DO UPDATE SET
    ssb_blob_ref = excluded.ssb_blob_ref,
    size = excluded.size,
    mime_type = excluded.mime_type
`

type AddBlobParams struct {
	AtCid      string
	SsbBlobRef string
	Size       sql.NullInt64
	MimeType   sql.NullString
}

func (q *Queries) AddBlob(ctx context.Context, arg AddBlobParams) error {
	_, err := q.db.ExecContext(ctx, addBlob,
		arg.AtCid,
		arg.SsbBlobRef,
		arg.Size,
		arg.MimeType,
	)
	return err
}

const countBlobSize = `-- name: CountBlobSize :one
SELECT COALESCE(SUM(size), 0) FROM blobs
`

func (q *Queries) CountBlobSize(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, countBlobSize)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const countBlobs = `-- name: CountBlobs :one
SELECT COUNT(*) FROM blobs
`

func (q *Queries) CountBlobs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBlobs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteBlob = `-- name: DeleteBlob :exec
DELETE FROM blobs WHERE at_cid = ?1
`

func (q *Queries) DeleteBlob(ctx context.Context, atCid string) error {
	_, err := q.db.ExecContext(ctx, deleteBlob, atCid)
	return err
}

const getBlob = `-- name: GetBlob :one
SELECT at_cid, ssb_blob_ref, size, mime_type, downloaded_at FROM blobs WHERE at_cid = ?1
`

func (q *Queries) GetBlob(ctx context.Context, atCid string) (Blob, error) {
	row := q.db.QueryRowContext(ctx, getBlob, atCid)
	var i Blob
	err := row.Scan(
		&i.AtCid,
		&i.SsbBlobRef,
		&i.Size,
		&i.MimeType,
		&i.DownloadedAt,
	)
	return i, err
}

const getBlobBySSBRef = `-- name: GetBlobBySSBRef :one
SELECT at_cid, ssb_blob_ref, size, mime_type, downloaded_at FROM blobs WHERE ssb_blob_ref = ?1
`

func (q *Queries) GetBlobBySSBRef(ctx context.Context, ssbBlobRef string) (Blob, error) {
	row := q.db.QueryRowContext(ctx, getBlobBySSBRef, ssbBlobRef)
	var i Blob
	err := row.Scan(
		&i.AtCid,
		&i.SsbBlobRef,
		&i.Size,
		&i.MimeType,
		&i.DownloadedAt,
	)
	return i, err
}

const getBlobsOlderThan = `-- name: GetBlobsOlderThan :many
SELECT at_cid, ssb_blob_ref, size, mime_type, downloaded_at FROM blobs
WHERE downloaded_at < datetime('now', '-' || ?1 || ' days')
ORDER BY downloaded_at ASC
`

func (q *Queries) GetBlobsOlderThan(ctx context.Context, days sql.NullString) ([]Blob, error) {
	rows, err := q.db.QueryContext(ctx, getBlobsOlderThan, days)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Blob
	for rows.Next() {
		var i Blob
		if err := rows.Scan(
			&i.AtCid,
			&i.SsbBlobRef,
			&i.Size,
			&i.MimeType,
			&i.DownloadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentBlobs = `-- name: GetRecentBlobs :many
SELECT at_cid, ssb_blob_ref, size, mime_type, downloaded_at FROM blobs
ORDER BY downloaded_at DESC
LIMIT ?1
`

func (q *Queries) GetRecentBlobs(ctx context.Context, limit int64) ([]Blob, error) {
	rows, err := q.db.QueryContext(ctx, getRecentBlobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Blob
	for rows.Next() {
		var i Blob
		if err := rows.Scan(
			&i.AtCid,
			&i.SsbBlobRef,
			&i.Size,
			&i.MimeType,
			&i.DownloadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
