// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dm.sql

package db

import (
	"context"
	"database/sql"
)

const getDMByKey = `-- name: GetDMByKey :one
SELECT id, ssb_msg_key, ssb_msg_seq, sender_feed, recipient_feed,
	   encrypted_content, plaintext, decrypted_at, created_at, received_at, is_outbound
FROM direct_messages
WHERE ssb_msg_key = ?
`

func (q *Queries) GetDMByKey(ctx context.Context, ssbMsgKey string) (DirectMessage, error) {
	row := q.db.QueryRowContext(ctx, getDMByKey, ssbMsgKey)
	var i DirectMessage
	err := row.Scan(
		&i.ID,
		&i.SsbMsgKey,
		&i.SsbMsgSeq,
		&i.SenderFeed,
		&i.RecipientFeed,
		&i.EncryptedContent,
		&i.Plaintext,
		&i.DecryptedAt,
		&i.CreatedAt,
		&i.ReceivedAt,
		&i.IsOutbound,
	)
	return i, err
}

const listDMConversations = `-- name: ListDMConversations :many
SELECT DISTINCT 
	CASE 
		WHEN sender_feed = ? THEN recipient_feed 
		ELSE sender_feed 
	END as other_party
FROM direct_messages
WHERE sender_feed = ? OR recipient_feed = ?
ORDER BY MAX(created_at) DESC
`

type ListDMConversationsParams struct {
	SenderFeed    string
	SenderFeed_2  string
	RecipientFeed string
}

func (q *Queries) ListDMConversations(ctx context.Context, arg ListDMConversationsParams) ([]interface{}, error) {
	rows, err := q.db.QueryContext(ctx, listDMConversations, arg.SenderFeed, arg.SenderFeed_2, arg.RecipientFeed)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []interface{}
	for rows.Next() {
		var other_party interface{}
		if err := rows.Scan(&other_party); err != nil {
			return nil, err
		}
		items = append(items, other_party)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDMsForFeed = `-- name: ListDMsForFeed :many
SELECT id, ssb_msg_key, ssb_msg_seq, sender_feed, recipient_feed,
	   encrypted_content, plaintext, decrypted_at, created_at, received_at, is_outbound
FROM direct_messages
WHERE sender_feed = ? OR recipient_feed = ?
ORDER BY created_at DESC
LIMIT ?
`

type ListDMsForFeedParams struct {
	SenderFeed    string
	RecipientFeed string
	Limit         int64
}

func (q *Queries) ListDMsForFeed(ctx context.Context, arg ListDMsForFeedParams) ([]DirectMessage, error) {
	rows, err := q.db.QueryContext(ctx, listDMsForFeed, arg.SenderFeed, arg.RecipientFeed, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DirectMessage
	for rows.Next() {
		var i DirectMessage
		if err := rows.Scan(
			&i.ID,
			&i.SsbMsgKey,
			&i.SsbMsgSeq,
			&i.SenderFeed,
			&i.RecipientFeed,
			&i.EncryptedContent,
			&i.Plaintext,
			&i.DecryptedAt,
			&i.CreatedAt,
			&i.ReceivedAt,
			&i.IsOutbound,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveDM = `-- name: SaveDM :exec
INSERT OR REPLACE INTO direct_messages (
	ssb_msg_key, ssb_msg_seq, sender_feed, recipient_feed,
	encrypted_content, plaintext, decrypted_at, created_at, received_at, is_outbound
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type SaveDMParams struct {
	SsbMsgKey        string
	SsbMsgSeq        sql.NullInt64
	SenderFeed       string
	RecipientFeed    string
	EncryptedContent []byte
	Plaintext        sql.NullString
	DecryptedAt      sql.NullTime
	CreatedAt        int64
	ReceivedAt       int64
	IsOutbound       bool
}

func (q *Queries) SaveDM(ctx context.Context, arg SaveDMParams) error {
	_, err := q.db.ExecContext(ctx, saveDM,
		arg.SsbMsgKey,
		arg.SsbMsgSeq,
		arg.SenderFeed,
		arg.RecipientFeed,
		arg.EncryptedContent,
		arg.Plaintext,
		arg.DecryptedAt,
		arg.CreatedAt,
		arg.ReceivedAt,
		arg.IsOutbound,
	)
	return err
}

const updateDMDecrypted = `-- name: UpdateDMDecrypted :exec
UPDATE direct_messages 
SET plaintext = ?, decrypted_at = ?
WHERE ssb_msg_key = ?
`

type UpdateDMDecryptedParams struct {
	Plaintext   sql.NullString
	DecryptedAt sql.NullTime
	SsbMsgKey   string
}

func (q *Queries) UpdateDMDecrypted(ctx context.Context, arg UpdateDMDecryptedParams) error {
	_, err := q.db.ExecContext(ctx, updateDMDecrypted, arg.Plaintext, arg.DecryptedAt, arg.SsbMsgKey)
	return err
}
