// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package db

import (
	"context"
	"database/sql"
)

const addMessage = `-- name: AddMessage :exec
INSERT INTO messages (
    at_uri, at_cid, ssb_msg_ref, at_did, type, message_state,
    raw_at_json, raw_ssb_json, published_at, publish_error,
    publish_attempts, last_publish_attempt_at, defer_reason,
    defer_attempts, last_defer_attempt_at, deleted_at,
    deleted_seq, deleted_reason, created_at
) VALUES (
    ?1, ?2, ?3, ?4, ?5, ?6,
    ?7, ?8, ?9, ?10,
    ?11, ?12, ?13,
    ?14, ?15, ?16,
    ?17, ?18, ?19
) ON CONFLICT(at_uri) DO UPDATE SET
    at_cid = excluded.at_cid,
    ssb_msg_ref = excluded.ssb_msg_ref,
    at_did = excluded.at_did,
    type = excluded.type,
    message_state = excluded.message_state,
    raw_at_json = excluded.raw_at_json,
    raw_ssb_json = excluded.raw_ssb_json,
    published_at = excluded.published_at,
    publish_error = excluded.publish_error,
    publish_attempts = messages.publish_attempts + excluded.publish_attempts,
    last_publish_attempt_at = excluded.last_publish_attempt_at,
    defer_reason = excluded.defer_reason,
    defer_attempts = messages.defer_attempts + excluded.defer_attempts,
    last_defer_attempt_at = excluded.last_defer_attempt_at,
    deleted_at = excluded.deleted_at,
    deleted_seq = excluded.deleted_seq,
    deleted_reason = excluded.deleted_reason
`

type AddMessageParams struct {
	AtUri                string
	AtCid                string
	SsbMsgRef            sql.NullString
	AtDid                string
	Type                 string
	MessageState         string
	RawAtJson            sql.NullString
	RawSsbJson           sql.NullString
	PublishedAt          sql.NullTime
	PublishError         sql.NullString
	PublishAttempts      int64
	LastPublishAttemptAt sql.NullTime
	DeferReason          sql.NullString
	DeferAttempts        int64
	LastDeferAttemptAt   sql.NullTime
	DeletedAt            sql.NullTime
	DeletedSeq           sql.NullInt64
	DeletedReason        sql.NullString
	CreatedAt            sql.NullTime
}

func (q *Queries) AddMessage(ctx context.Context, arg AddMessageParams) error {
	_, err := q.db.ExecContext(ctx, addMessage,
		arg.AtUri,
		arg.AtCid,
		arg.SsbMsgRef,
		arg.AtDid,
		arg.Type,
		arg.MessageState,
		arg.RawAtJson,
		arg.RawSsbJson,
		arg.PublishedAt,
		arg.PublishError,
		arg.PublishAttempts,
		arg.LastPublishAttemptAt,
		arg.DeferReason,
		arg.DeferAttempts,
		arg.LastDeferAttemptAt,
		arg.DeletedAt,
		arg.DeletedSeq,
		arg.DeletedReason,
		arg.CreatedAt,
	)
	return err
}

const countDeferredMessages = `-- name: CountDeferredMessages :one
SELECT COUNT(*) FROM messages WHERE message_state = 'deferred'
`

func (q *Queries) CountDeferredMessages(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDeferredMessages)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDeletedMessages = `-- name: CountDeletedMessages :one
SELECT COUNT(*) FROM messages WHERE message_state = 'deleted'
`

func (q *Queries) CountDeletedMessages(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDeletedMessages)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMessages = `-- name: CountMessages :one
SELECT COUNT(*) FROM messages
`

func (q *Queries) CountMessages(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMessages)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMessagesByDID = `-- name: CountMessagesByDID :one
SELECT COUNT(*) FROM messages WHERE at_did = ?1
`

func (q *Queries) CountMessagesByDID(ctx context.Context, atDid string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMessagesByDID, atDid)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPublishFailures = `-- name: CountPublishFailures :one
SELECT COUNT(*) FROM messages WHERE message_state = 'failed'
`

func (q *Queries) CountPublishFailures(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPublishFailures)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPublishedMessages = `-- name: CountPublishedMessages :one
SELECT COUNT(*) FROM messages WHERE ssb_msg_ref IS NOT NULL AND ssb_msg_ref <> ''
`

func (q *Queries) CountPublishedMessages(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPublishedMessages)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getDeferredCandidates = `-- name: GetDeferredCandidates :many
SELECT at_uri, at_cid, ssb_msg_ref, at_did, type, message_state, raw_at_json, raw_ssb_json, published_at, publish_error, publish_attempts, last_publish_attempt_at, defer_reason, defer_attempts, last_defer_attempt_at, deleted_at, deleted_seq, deleted_reason, created_at FROM messages
WHERE message_state = 'deferred'
ORDER BY last_defer_attempt_at ASC
LIMIT ?1
`

func (q *Queries) GetDeferredCandidates(ctx context.Context, limit int64) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getDeferredCandidates, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.AtUri,
			&i.AtCid,
			&i.SsbMsgRef,
			&i.AtDid,
			&i.Type,
			&i.MessageState,
			&i.RawAtJson,
			&i.RawSsbJson,
			&i.PublishedAt,
			&i.PublishError,
			&i.PublishAttempts,
			&i.LastPublishAttemptAt,
			&i.DeferReason,
			&i.DeferAttempts,
			&i.LastDeferAttemptAt,
			&i.DeletedAt,
			&i.DeletedSeq,
			&i.DeletedReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestDeferredReason = `-- name: GetLatestDeferredReason :one
SELECT defer_reason FROM messages
WHERE message_state = 'deferred' AND defer_reason IS NOT NULL AND defer_reason <> ''
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestDeferredReason(ctx context.Context) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getLatestDeferredReason)
	var defer_reason sql.NullString
	err := row.Scan(&defer_reason)
	return defer_reason, err
}

const getMessage = `-- name: GetMessage :one
SELECT at_uri, at_cid, ssb_msg_ref, at_did, type, message_state, raw_at_json, raw_ssb_json, published_at, publish_error, publish_attempts, last_publish_attempt_at, defer_reason, defer_attempts, last_defer_attempt_at, deleted_at, deleted_seq, deleted_reason, created_at FROM messages WHERE at_uri = ?1
`

func (q *Queries) GetMessage(ctx context.Context, atUri string) (Message, error) {
	row := q.db.QueryRowContext(ctx, getMessage, atUri)
	var i Message
	err := row.Scan(
		&i.AtUri,
		&i.AtCid,
		&i.SsbMsgRef,
		&i.AtDid,
		&i.Type,
		&i.MessageState,
		&i.RawAtJson,
		&i.RawSsbJson,
		&i.PublishedAt,
		&i.PublishError,
		&i.PublishAttempts,
		&i.LastPublishAttemptAt,
		&i.DeferReason,
		&i.DeferAttempts,
		&i.LastDeferAttemptAt,
		&i.DeletedAt,
		&i.DeletedSeq,
		&i.DeletedReason,
		&i.CreatedAt,
	)
	return i, err
}

const getPublishFailures = `-- name: GetPublishFailures :many
SELECT at_uri, at_cid, ssb_msg_ref, at_did, type, message_state, raw_at_json, raw_ssb_json, published_at, publish_error, publish_attempts, last_publish_attempt_at, defer_reason, defer_attempts, last_defer_attempt_at, deleted_at, deleted_seq, deleted_reason, created_at FROM messages
WHERE message_state IN ('failed', 'deferred')
ORDER BY COALESCE(last_publish_attempt_at, last_defer_attempt_at, created_at) DESC
LIMIT ?1
`

func (q *Queries) GetPublishFailures(ctx context.Context, limit int64) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getPublishFailures, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.AtUri,
			&i.AtCid,
			&i.SsbMsgRef,
			&i.AtDid,
			&i.Type,
			&i.MessageState,
			&i.RawAtJson,
			&i.RawSsbJson,
			&i.PublishedAt,
			&i.PublishError,
			&i.PublishAttempts,
			&i.LastPublishAttemptAt,
			&i.DeferReason,
			&i.DeferAttempts,
			&i.LastDeferAttemptAt,
			&i.DeletedAt,
			&i.DeletedSeq,
			&i.DeletedReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentMessages = `-- name: GetRecentMessages :many
SELECT at_uri, at_cid, ssb_msg_ref, at_did, type, message_state, raw_at_json, raw_ssb_json, published_at, publish_error, publish_attempts, last_publish_attempt_at, defer_reason, defer_attempts, last_defer_attempt_at, deleted_at, deleted_seq, deleted_reason, created_at FROM messages
ORDER BY created_at DESC
LIMIT ?1
`

func (q *Queries) GetRecentMessages(ctx context.Context, limit int64) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getRecentMessages, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.AtUri,
			&i.AtCid,
			&i.SsbMsgRef,
			&i.AtDid,
			&i.Type,
			&i.MessageState,
			&i.RawAtJson,
			&i.RawSsbJson,
			&i.PublishedAt,
			&i.PublishError,
			&i.PublishAttempts,
			&i.LastPublishAttemptAt,
			&i.DeferReason,
			&i.DeferAttempts,
			&i.LastDeferAttemptAt,
			&i.DeletedAt,
			&i.DeletedSeq,
			&i.DeletedReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRetryCandidates = `-- name: GetRetryCandidates :many
SELECT at_uri, at_cid, ssb_msg_ref, at_did, type, message_state, raw_at_json, raw_ssb_json, published_at, publish_error, publish_attempts, last_publish_attempt_at, defer_reason, defer_attempts, last_defer_attempt_at, deleted_at, deleted_seq, deleted_reason, created_at FROM messages
WHERE message_state = 'failed'
AND (?1 = '' OR at_did = ?1)
AND publish_attempts < ?2
ORDER BY last_publish_attempt_at ASC
LIMIT ?3
`

type GetRetryCandidatesParams struct {
	AtDid       interface{}
	MaxAttempts int64
	Limit       int64
}

func (q *Queries) GetRetryCandidates(ctx context.Context, arg GetRetryCandidatesParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getRetryCandidates, arg.AtDid, arg.MaxAttempts, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.AtUri,
			&i.AtCid,
			&i.SsbMsgRef,
			&i.AtDid,
			&i.Type,
			&i.MessageState,
			&i.RawAtJson,
			&i.RawSsbJson,
			&i.PublishedAt,
			&i.PublishError,
			&i.PublishAttempts,
			&i.LastPublishAttemptAt,
			&i.DeferReason,
			&i.DeferAttempts,
			&i.LastDeferAttemptAt,
			&i.DeletedAt,
			&i.DeletedSeq,
			&i.DeletedReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessageTypes = `-- name: ListMessageTypes :many
SELECT DISTINCT type FROM messages ORDER BY type
`

func (q *Queries) ListMessageTypes(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listMessageTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var type_ string
		if err := rows.Scan(&type_); err != nil {
			return nil, err
		}
		items = append(items, type_)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedMessagesGlobal = `-- name: ListPublishedMessagesGlobal :many
SELECT at_uri, at_cid, ssb_msg_ref, at_did, type, message_state, raw_at_json, raw_ssb_json, published_at, publish_error, publish_attempts, last_publish_attempt_at, defer_reason, defer_attempts, last_defer_attempt_at, deleted_at, deleted_seq, deleted_reason, created_at FROM messages
WHERE ssb_msg_ref IS NOT NULL AND ssb_msg_ref <> ''
ORDER BY published_at DESC
LIMIT ?1
`

func (q *Queries) ListPublishedMessagesGlobal(ctx context.Context, limit int64) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listPublishedMessagesGlobal, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.AtUri,
			&i.AtCid,
			&i.SsbMsgRef,
			&i.AtDid,
			&i.Type,
			&i.MessageState,
			&i.RawAtJson,
			&i.RawSsbJson,
			&i.PublishedAt,
			&i.PublishError,
			&i.PublishAttempts,
			&i.LastPublishAttemptAt,
			&i.DeferReason,
			&i.DeferAttempts,
			&i.LastDeferAttemptAt,
			&i.DeletedAt,
			&i.DeletedSeq,
			&i.DeletedReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentPublishedMessagesByDID = `-- name: ListRecentPublishedMessagesByDID :many
SELECT at_uri, at_cid, ssb_msg_ref, at_did, type, message_state, raw_at_json, raw_ssb_json, published_at, publish_error, publish_attempts, last_publish_attempt_at, defer_reason, defer_attempts, last_defer_attempt_at, deleted_at, deleted_seq, deleted_reason, created_at FROM messages
WHERE at_did = ?1 AND ssb_msg_ref IS NOT NULL AND ssb_msg_ref <> ''
ORDER BY published_at DESC
LIMIT ?2
`

type ListRecentPublishedMessagesByDIDParams struct {
	AtDid string
	Limit int64
}

func (q *Queries) ListRecentPublishedMessagesByDID(ctx context.Context, arg ListRecentPublishedMessagesByDIDParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listRecentPublishedMessagesByDID, arg.AtDid, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.AtUri,
			&i.AtCid,
			&i.SsbMsgRef,
			&i.AtDid,
			&i.Type,
			&i.MessageState,
			&i.RawAtJson,
			&i.RawSsbJson,
			&i.PublishedAt,
			&i.PublishError,
			&i.PublishAttempts,
			&i.LastPublishAttemptAt,
			&i.DeferReason,
			&i.DeferAttempts,
			&i.LastDeferAttemptAt,
			&i.DeletedAt,
			&i.DeletedSeq,
			&i.DeletedReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopDeferredReasons = `-- name: ListTopDeferredReasons :many
SELECT defer_reason as reason, COUNT(*) as count
FROM messages
WHERE message_state = 'deferred' AND defer_reason IS NOT NULL AND defer_reason <> ''
GROUP BY defer_reason
ORDER BY count DESC
LIMIT ?1
`

type ListTopDeferredReasonsRow struct {
	Reason sql.NullString
	Count  int64
}

func (q *Queries) ListTopDeferredReasons(ctx context.Context, limit int64) ([]ListTopDeferredReasonsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTopDeferredReasons, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTopDeferredReasonsRow
	for rows.Next() {
		var i ListTopDeferredReasonsRow
		if err := rows.Scan(&i.Reason, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopIssueAccounts = `-- name: ListTopIssueAccounts :many
SELECT
  ba.at_did,
  ba.ssb_feed_id,
  ba.active,
  COALESCE(s.total_messages, 0) as total_messages,
  COALESCE(s.issue_messages, 0) as issue_messages,
  COALESCE(s.failed_messages, 0) as failed_messages,
  COALESCE(s.deferred_messages, 0) as deferred_count
FROM bridged_accounts ba
LEFT JOIN (
  SELECT
    at_did,
    COUNT(*) as total_messages,
    SUM(CASE WHEN message_state IN ('failed', 'deferred') THEN 1 ELSE 0 END) as issue_messages,
    SUM(CASE WHEN message_state = 'failed' THEN 1 ELSE 0 END) as failed_messages,
    SUM(CASE WHEN message_state = 'deferred' THEN 1 ELSE 0 END) as deferred_messages
  FROM messages
  GROUP BY at_did
) s ON s.at_did = ba.at_did
WHERE s.issue_messages > 0
ORDER BY s.issue_messages DESC
LIMIT ?1
`

type ListTopIssueAccountsRow struct {
	AtDid          string
	SsbFeedID      string
	Active         sql.NullBool
	TotalMessages  int64
	IssueMessages  float64
	FailedMessages float64
	DeferredCount  float64
}

func (q *Queries) ListTopIssueAccounts(ctx context.Context, limit int64) ([]ListTopIssueAccountsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTopIssueAccounts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTopIssueAccountsRow
	for rows.Next() {
		var i ListTopIssueAccountsRow
		if err := rows.Scan(
			&i.AtDid,
			&i.SsbFeedID,
			&i.Active,
			&i.TotalMessages,
			&i.IssueMessages,
			&i.FailedMessages,
			&i.DeferredCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetMessageForRetry = `-- name: ResetMessageForRetry :exec
UPDATE messages SET
  message_state = 'pending',
  publish_error = '',
  publish_attempts = 0,
  last_publish_attempt_at = NULL
WHERE at_uri = ?1
`

func (q *Queries) ResetMessageForRetry(ctx context.Context, atUri string) error {
	_, err := q.db.ExecContext(ctx, resetMessageForRetry, atUri)
	return err
}
