// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type AtprotoCommitBuffer struct {
	ID           int64
	Did          string
	Generation   int64
	Rev          string
	Seq          int64
	RawEventJson string
	CreatedAt    sql.NullTime
}

type AtprotoEventLog struct {
	Cursor     int64
	Did        string
	Collection string
	Rkey       string
	AtUri      string
	AtCid      sql.NullString
	Action     string
	Live       bool
	Rev        sql.NullString
	Seq        sql.NullInt64
	RecordJson sql.NullString
	CreatedAt  sql.NullTime
}

type AtprotoRecord struct {
	Did        string
	Collection string
	Rkey       string
	AtUri      string
	AtCid      string
	RecordJson string
	LastRev    sql.NullString
	LastSeq    sql.NullInt64
	Deleted    bool
	DeletedAt  sql.NullTime
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
}

type AtprotoRepo struct {
	Did              string
	Tracking         bool
	Reason           sql.NullString
	SyncState        string
	Generation       int64
	CurrentRev       sql.NullString
	CurrentCommitCid sql.NullString
	CurrentDataCid   sql.NullString
	LastFirehoseSeq  sql.NullInt64
	LastBackfillAt   sql.NullTime
	LastEventCursor  sql.NullInt64
	Handle           sql.NullString
	PdsUrl           sql.NullString
	AccountActive    sql.NullBool
	AccountStatus    sql.NullString
	LastIdentityAt   sql.NullTime
	LastAccountAt    sql.NullTime
	LastError        sql.NullString
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
}

type AtprotoSource struct {
	SourceKey   string
	RelayUrl    string
	LastSeq     int64
	ConnectedAt sql.NullTime
	UpdatedAt   sql.NullTime
}

type Blob struct {
	AtCid        string
	SsbBlobRef   string
	Size         sql.NullInt64
	MimeType     sql.NullString
	DownloadedAt sql.NullTime
}

type BridgeState struct {
	Key       string
	Value     string
	UpdatedAt sql.NullTime
}

type BridgedAccount struct {
	AtDid     string
	SsbFeedID string
	CreatedAt sql.NullTime
	Active    sql.NullBool
}

type DirectMessage struct {
	ID               int64
	SsbMsgKey        string
	SsbMsgSeq        sql.NullInt64
	SenderFeed       string
	RecipientFeed    string
	EncryptedContent []byte
	Plaintext        sql.NullString
	DecryptedAt      sql.NullTime
	CreatedAt        int64
	ReceivedAt       int64
	IsOutbound       bool
}

type KnownPeer struct {
	Addr      string
	Pubkey    []byte
	LastSeen  sql.NullTime
	CreatedAt sql.NullTime
}

type Message struct {
	AtUri                string
	AtCid                string
	SsbMsgRef            sql.NullString
	AtDid                string
	Type                 string
	MessageState         string
	RawAtJson            sql.NullString
	RawSsbJson           sql.NullString
	PublishedAt          sql.NullTime
	PublishError         sql.NullString
	PublishAttempts      int64
	LastPublishAttemptAt sql.NullTime
	DeferReason          sql.NullString
	DeferAttempts        int64
	LastDeferAttemptAt   sql.NullTime
	DeletedAt            sql.NullTime
	DeletedSeq           sql.NullInt64
	DeletedReason        sql.NullString
	CreatedAt            sql.NullTime
}

type SchemaMigration struct {
	Version     int64
	AppliedAt   sql.NullTime
	Description sql.NullString
}

type SsbFollowerSync struct {
	BotDid          string
	FollowerSsbFeed string
	FollowedBackAt  sql.NullTime
}
