// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: peers.sql

package db

import (
	"context"
	"database/sql"
)

const addKnownPeer = `-- name: AddKnownPeer :exec
INSERT INTO known_peers (addr, pubkey, last_seen)
VALUES (?, ?, ?)
ON CONFLICT(addr) DO UPDATE SET pubkey=excluded.pubkey, last_seen=excluded.last_seen
`

type AddKnownPeerParams struct {
	Addr     string
	Pubkey   []byte
	LastSeen sql.NullTime
}

func (q *Queries) AddKnownPeer(ctx context.Context, arg AddKnownPeerParams) error {
	_, err := q.db.ExecContext(ctx, addKnownPeer, arg.Addr, arg.Pubkey, arg.LastSeen)
	return err
}

const getKnownPeers = `-- name: GetKnownPeers :many
SELECT addr, pubkey, last_seen, created_at FROM known_peers ORDER BY created_at DESC
`

func (q *Queries) GetKnownPeers(ctx context.Context) ([]KnownPeer, error) {
	rows, err := q.db.QueryContext(ctx, getKnownPeers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KnownPeer
	for rows.Next() {
		var i KnownPeer
		if err := rows.Scan(
			&i.Addr,
			&i.Pubkey,
			&i.LastSeen,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
