// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: state.sql

package db

import (
	"context"
)

const getAllBridgeState = `-- name: GetAllBridgeState :many
SELECT key, value, updated_at FROM bridge_state ORDER BY key ASC
`

func (q *Queries) GetAllBridgeState(ctx context.Context) ([]BridgeState, error) {
	rows, err := q.db.QueryContext(ctx, getAllBridgeState)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BridgeState
	for rows.Next() {
		var i BridgeState
		if err := rows.Scan(&i.Key, &i.Value, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBridgeHealth = `-- name: GetBridgeHealth :one
SELECT value FROM bridge_state WHERE key = 'bridge_runtime_status'
`

func (q *Queries) GetBridgeHealth(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getBridgeHealth)
	var value string
	err := row.Scan(&value)
	return value, err
}

const getBridgeHeartbeat = `-- name: GetBridgeHeartbeat :one
SELECT value FROM bridge_state WHERE key = 'bridge_runtime_last_heartbeat_at'
`

func (q *Queries) GetBridgeHeartbeat(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getBridgeHeartbeat)
	var value string
	err := row.Scan(&value)
	return value, err
}

const getBridgeState = `-- name: GetBridgeState :one
SELECT key, value, updated_at FROM bridge_state WHERE key = ?
`

func (q *Queries) GetBridgeState(ctx context.Context, key string) (BridgeState, error) {
	row := q.db.QueryRowContext(ctx, getBridgeState, key)
	var i BridgeState
	err := row.Scan(&i.Key, &i.Value, &i.UpdatedAt)
	return i, err
}

const setBridgeState = `-- name: SetBridgeState :exec
INSERT INTO bridge_state (key, value, updated_at)
VALUES (?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(key) DO UPDATE SET value=excluded.value, updated_at=CURRENT_TIMESTAMP
`

type SetBridgeStateParams struct {
	Key   string
	Value string
}

func (q *Queries) SetBridgeState(ctx context.Context, arg SetBridgeStateParams) error {
	_, err := q.db.ExecContext(ctx, setBridgeState, arg.Key, arg.Value)
	return err
}
